var searchData=
[
  ['c_20module_20development_0',['Classes related to C++ module development.',['../group__Module.html',1,'']]],
  ['c_20sdk_1',['Viam C++ SDK',['../index.html',1,'']]],
  ['camera_2',['Camera',['../classviam_1_1sdk_1_1Camera.html',1,'viam::sdk']]],
  ['camera_3',['camera',['../structviam_1_1sdk_1_1obstacle__detector.html#a5a13275f9db9504b50843192ed740c22',1,'viam::sdk::obstacle_detector']]],
  ['camera_2ehpp_4',['camera.hpp',['../camera_8hpp.html',1,'']]],
  ['camera_5fclient_2ehpp_5',['camera_client.hpp',['../camera__client_8hpp.html',1,'']]],
  ['camera_5fserver_2ehpp_6',['camera_server.hpp',['../camera__server_8hpp.html',1,'']]],
  ['cameraclient_7',['CameraClient',['../classviam_1_1sdk_1_1impl_1_1CameraClient.html',1,'viam::sdk::impl']]],
  ['cameraserver_8',['CameraServer',['../classviam_1_1sdk_1_1impl_1_1CameraServer.html',1,'viam::sdk::impl']]],
  ['cancel_5foperation_9',['cancel_operation',['../classviam_1_1sdk_1_1RobotClient.html#a5f95ba72f3142fed2b648c93ad92f3c0',1,'viam::sdk::RobotClient']]],
  ['capsule_10',['capsule',['../structviam_1_1sdk_1_1capsule.html',1,'viam::sdk']]],
  ['classes_20related_20to_20a_20robot_20representation_11',['Classes related to a Robot representation.',['../group__Robot.html',1,'']]],
  ['classes_20related_20to_20c_20module_20development_12',['Classes related to C++ module development.',['../group__Module.html',1,'']]],
  ['classes_20related_20to_20logging_13',['Classes related to logging',['../group__Log.html',1,'']]],
  ['classes_20related_20to_20sdk_20exceptions_14',['Classes related to SDK exceptions.',['../group__Exception.html',1,'']]],
  ['classes_20related_20to_20the_20arm_20component_15',['Classes related to the Arm component.',['../group__Arm.html',1,'']]],
  ['classes_20related_20to_20the_20audioin_20component_16',['Classes related to the AudioIn component.',['../group__Base.html',1,'']]],
  ['classes_20related_20to_20the_20audioout_20component_17',['Classes related to the AudioOut component.',['../group__AudioOut.html',1,'']]],
  ['classes_20related_20to_20the_20button_20component_18',['Classes related to the Button component.',['../group__Button.html',1,'']]],
  ['classes_20related_20to_20the_20discovery_20service_19',['Classes related to the Discovery service.',['../group__Discovery.html',1,'']]],
  ['classes_20related_20to_20the_20gantry_20component_20',['Classes related to the Gantry component',['../group__Gantry.html',1,'']]],
  ['classes_20related_20to_20the_20gripper_20component_21',['Classes related to the Gripper component.',['../group__Gripper.html',1,'']]],
  ['classes_20related_20to_20the_20movementsensor_20component_22',['Classes related to the MovementSensor component.',['../group__MovementSensor.html',1,'']]],
  ['classes_20related_20to_20the_20posetracker_20component_23',['Classes related to the PoseTracker component.',['../group__PoseTracker.html',1,'']]],
  ['classes_20related_20to_20the_20powersensor_20component_24',['Classes related to the PowerSensor component.',['../group__PowerSensor.html',1,'']]],
  ['classes_20related_20to_20the_20sensor_20component_25',['Classes related to the Sensor component.',['../group__Sensor.html',1,'']]],
  ['classes_20related_20to_20the_20servo_20component_26',['Classes related to the Servo component.',['../group__Servo.html',1,'']]],
  ['classes_20related_20to_20the_20switch_20component_27',['Classes related to the Switch component.',['../group__Switch.html',1,'']]],
  ['client_2ehpp_28',['client.hpp',['../client_8hpp.html',1,'']]],
  ['clientcontext_29',['ClientContext',['../classviam_1_1sdk_1_1ClientContext.html',1,'viam::sdk']]],
  ['clienthelper_30',['ClientHelper',['../classviam_1_1sdk_1_1ClientHelper.html',1,'viam::sdk']]],
  ['close_31',['close',['../classviam_1_1sdk_1_1RobotClient.html#a282c43833b86045f77f14aff324d173f',1,'viam::sdk::RobotClient']]],
  ['collision_5fspecification_32',['collision_specification',['../structviam_1_1sdk_1_1Motion_1_1collision__specification.html',1,'viam::sdk::Motion']]],
  ['compassheading_33',['compassheading',['../structviam_1_1sdk_1_1MovementSensor_1_1compassheading.html',1,'viam::sdk::MovementSensor']]],
  ['component_34',['component',['../group__Arm.html',1,'Classes related to the Arm component.'],['../group__Base.html',1,'Classes related to the AudioIn component.'],['../group__AudioOut.html',1,'Classes related to the AudioOut component.'],['../group__Button.html',1,'Classes related to the Button component.'],['../group__Gantry.html',1,'Classes related to the Gantry component'],['../group__Gripper.html',1,'Classes related to the Gripper component.'],['../group__MovementSensor.html',1,'Classes related to the MovementSensor component.'],['../group__PoseTracker.html',1,'Classes related to the PoseTracker component.'],['../group__PowerSensor.html',1,'Classes related to the PowerSensor component.'],['../group__Sensor.html',1,'Classes related to the Sensor component.'],['../group__Servo.html',1,'Classes related to the Servo component.'],['../group__Switch.html',1,'Classes related to the Switch component.']]],
  ['component_35',['Component',['../classviam_1_1sdk_1_1Component.html',1,'viam::sdk']]],
  ['component_5fname_36',['component_name',['../structviam_1_1sdk_1_1Motion_1_1plan__status__with__id.html#a938900876ca30090794822e7ee1eb178',1,'viam::sdk::Motion::plan_status_with_id::component_name'],['../structviam_1_1sdk_1_1Motion_1_1plan.html#a62bc1d9a42ed4a7f09eba4d377633403',1,'viam::sdk::Motion::plan::component_name']]],
  ['connectivity_20and_20webrtc_20functionality_37',['A Note on Connectivity and webRTC Functionality',['../index.html#autotoc_md6',1,'']]],
  ['constraints_38',['constraints',['../structviam_1_1sdk_1_1Motion_1_1constraints.html',1,'viam::sdk::Motion']]],
  ['construct_5fresource_39',['construct_resource',['../classviam_1_1sdk_1_1ModelRegistration.html#a4089b61b35308baec8f6bf3c116c82aa',1,'viam::sdk::ModelRegistration']]],
  ['coordinates_40',['coordinates',['../structviam_1_1sdk_1_1coordinates.html',1,'viam::sdk']]],
  ['create_5fresource_5fserver_41',['create_resource_server',['../classviam_1_1sdk_1_1ResourceServerRegistration.html#ac29e547bd2badcc93001233b9bd495cd',1,'viam::sdk::ResourceServerRegistration']]],
  ['create_5frpc_5fclient_42',['create_rpc_client',['../classviam_1_1sdk_1_1ResourceClientRegistration.html#a2f791b6faca0f11dae7f7c03927b9d52',1,'viam::sdk::ResourceClientRegistration']]],
  ['creation_43',['Creation',['../classviam_1_1sdk_1_1Instance.html#a8a82a81310c4339011555fbe15689aa8',1,'viam::sdk::Instance']]],
  ['credentials_44',['Credentials',['../classviam_1_1sdk_1_1Credentials.html',1,'viam::sdk']]],
  ['current_45',['current',['../structviam_1_1sdk_1_1PowerSensor_1_1current.html',1,'viam::sdk::PowerSensor::current'],['../classviam_1_1sdk_1_1Instance.html#a39639c15c58001c546d82db34c070f8e',1,'viam::sdk::Instance::current()']]]
];
