// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: component/sensor/v1/sensor.proto

#include "component/sensor/v1/sensor.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace viam {
namespace component {
namespace sensor {
namespace v1 {
}  // namespace v1
}  // namespace sensor
}  // namespace component
}  // namespace viam
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_component_2fsensor_2fv1_2fsensor_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_component_2fsensor_2fv1_2fsensor_2eproto = nullptr;
const uint32_t TableStruct_component_2fsensor_2fv1_2fsensor_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_component_2fsensor_2fv1_2fsensor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n component/sensor/v1/sensor.proto\022\030viam"
  ".component.sensor.v1\032\026common/v1/common.p"
  "roto\032\034google/api/annotations.proto2\303\003\n\rS"
  "ensorService\022\215\001\n\013GetReadings\022\".viam.comm"
  "on.v1.GetReadingsRequest\032#.viam.common.v"
  "1.GetReadingsResponse\"5\202\323\344\223\002/\022-/viam/api"
  "/v1/component/sensor/{name}/readings\022\211\001\n"
  "\tDoCommand\022 .viam.common.v1.DoCommandReq"
  "uest\032!.viam.common.v1.DoCommandResponse\""
  "7\202\323\344\223\0021\"//viam/api/v1/component/sensor/{"
  "name}/do_command\022\225\001\n\rGetGeometries\022$.via"
  "m.common.v1.GetGeometriesRequest\032%.viam."
  "common.v1.GetGeometriesResponse\"7\202\323\344\223\0021\022"
  "//viam/api/v1/component/sensor/{name}/ge"
  "ometriesBC\n\034com.viam.component.sensor.v1"
  "Z#go.viam.com/api/component/sensor/v1b\006p"
  "roto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto_deps[2] = {
  &::descriptor_table_common_2fv1_2fcommon_2eproto,
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
};
static ::_pbi::once_flag descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto = {
    false, false, 645, descriptor_table_protodef_component_2fsensor_2fv1_2fsensor_2eproto,
    "component/sensor/v1/sensor.proto",
    &descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto_once, descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto_deps, 2, 0,
    schemas, file_default_instances, TableStruct_component_2fsensor_2fv1_2fsensor_2eproto::offsets,
    nullptr, file_level_enum_descriptors_component_2fsensor_2fv1_2fsensor_2eproto,
    file_level_service_descriptors_component_2fsensor_2fv1_2fsensor_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto_getter() {
  return &descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_component_2fsensor_2fv1_2fsensor_2eproto(&descriptor_table_component_2fsensor_2fv1_2fsensor_2eproto);
namespace viam {
namespace component {
namespace sensor {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace sensor
}  // namespace component
}  // namespace viam
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
