# n.b. this is primarily a duplicate of the Dockerfile one level up, but with an
# additional entrypoint for running tests. Not ideal, but sufficient for CI purposes.
# We should at some point fix this.
FROM debian:bullseye

ENV HOME /root
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get -y dist-upgrade

RUN apt-get -y --no-install-recommends install \
    build-essential \
    ca-certificates \
    curl \
    doxygen \
    g++ \
    gdb \
    git \
    gnupg \
    gpg \
    less \
    libabsl-dev \
    libboost-all-dev \
    libgrpc++-dev \
    libprotobuf-dev \
    libssl-dev \
    ninja-build \
    pkg-config \
    protobuf-compiler-grpc \
    software-properties-common \
    sudo \
    wget

# Add the public key for the llvm repository
RUN bash -c 'wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -'
RUN apt-add-repository -y 'deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-15 main'
RUN apt-add-repository -y 'deb http://deb.debian.org/debian bullseye-backports main'

RUN apt-get update

RUN apt-get -y --no-install-recommends install -t llvm-toolchain-bullseye-15 \
    clang-15 \
    clang-tidy-15

RUN apt-get -y --no-install-recommends install -t bullseye-backports \
    cmake

COPY . /tmp/
ENTRYPOINT ["etc/docker/tests/run_test.sh"]
