FROM debian:sid

ENV HOME /root
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get -y dist-upgrade

RUN apt-get -y --no-install-recommends install \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    doxygen \
    curl \
    g++ \
    gdb \
    git \
    less \
    libboost-all-dev \
    libgrpc++-dev \
    libprotobuf-dev \
    libssl-dev \
    libxtensor-dev \
    ninja-build \
    pkg-config \
    protobuf-compiler-grpc \
    wget
