// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: component/posetracker/v1/pose_tracker.proto
// Protobuf C++ Version: 6.33.4

#ifndef component_2fposetracker_2fv1_2fpose_5ftracker_2eproto_2epb_2eh
#define component_2fposetracker_2fv1_2fpose_5ftracker_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
#include "common/v1/common.pb.h"
#include "google/api/annotations.pb.h"
#include "google/protobuf/struct.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_component_2fposetracker_2fv1_2fpose_5ftracker_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_component_2fposetracker_2fv1_2fpose_5ftracker_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_component_2fposetracker_2fv1_2fpose_5ftracker_2eproto;
}  // extern "C"
namespace viam {
namespace component {
namespace posetracker {
namespace v1 {
class GetPosesRequest;
struct GetPosesRequestDefaultTypeInternal;
extern GetPosesRequestDefaultTypeInternal _GetPosesRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetPosesRequest_class_data_;
class GetPosesResponse;
struct GetPosesResponseDefaultTypeInternal;
extern GetPosesResponseDefaultTypeInternal _GetPosesResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetPosesResponse_class_data_;
class GetPosesResponse_BodyPosesEntry_DoNotUse;
struct GetPosesResponse_BodyPosesEntry_DoNotUseDefaultTypeInternal;
extern GetPosesResponse_BodyPosesEntry_DoNotUseDefaultTypeInternal _GetPosesResponse_BodyPosesEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetPosesResponse_BodyPosesEntry_DoNotUse_class_data_;
}  // namespace v1
}  // namespace posetracker
}  // namespace component
}  // namespace viam
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace viam {
namespace component {
namespace posetracker {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class GetPosesRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:viam.component.posetracker.v1.GetPosesRequest) */ {
 public:
  inline GetPosesRequest() : GetPosesRequest(nullptr) {}
  ~GetPosesRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetPosesRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetPosesRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetPosesRequest(::google::protobuf::internal::ConstantInitialized);

  inline GetPosesRequest(const GetPosesRequest& from) : GetPosesRequest(nullptr, from) {}
  inline GetPosesRequest(GetPosesRequest&& from) noexcept
      : GetPosesRequest(nullptr, ::std::move(from)) {}
  inline GetPosesRequest& operator=(const GetPosesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPosesRequest& operator=(GetPosesRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPosesRequest& default_instance() {
    return *reinterpret_cast<const GetPosesRequest*>(
        &_GetPosesRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GetPosesRequest& a, GetPosesRequest& b) { a.Swap(&b); }
  inline void Swap(GetPosesRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPosesRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPosesRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetPosesRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetPosesRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetPosesRequest& from) { GetPosesRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetPosesRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "viam.component.posetracker.v1.GetPosesRequest"; }

  explicit GetPosesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetPosesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetPosesRequest& from);
  GetPosesRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetPosesRequest&& from) noexcept
      : GetPosesRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBodyNamesFieldNumber = 2,
    kNameFieldNumber = 1,
    kExtraFieldNumber = 99,
  };
  // repeated string body_names = 2 [json_name = "bodyNames"];
  int body_names_size() const;
  private:
  int _internal_body_names_size() const;

  public:
  void clear_body_names() ;
  const ::std::string& body_names(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_body_names(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_body_names(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_body_names();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_body_names(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& body_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_body_names();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_body_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_body_names();

  public:
  // string name = 1 [json_name = "name"];
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .google.protobuf.Struct extra = 99 [json_name = "extra"];
  bool has_extra() const;
  void clear_extra() ;
  const ::google::protobuf::Struct& extra() const;
  [[nodiscard]] ::google::protobuf::Struct* PROTOBUF_NULLABLE release_extra();
  ::google::protobuf::Struct* PROTOBUF_NONNULL mutable_extra();
  void set_allocated_extra(::google::protobuf::Struct* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_extra(::google::protobuf::Struct* PROTOBUF_NULLABLE value);
  ::google::protobuf::Struct* PROTOBUF_NULLABLE unsafe_arena_release_extra();

  private:
  const ::google::protobuf::Struct& _internal_extra() const;
  ::google::protobuf::Struct* PROTOBUF_NONNULL _internal_mutable_extra();

  public:
  // @@protoc_insertion_point(class_scope:viam.component.posetracker.v1.GetPosesRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 68,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetPosesRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> body_names_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::Struct* PROTOBUF_NULLABLE extra_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_component_2fposetracker_2fv1_2fpose_5ftracker_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetPosesRequest_class_data_;
// -------------------------------------------------------------------

class GetPosesResponse_BodyPosesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  GetPosesResponse_BodyPosesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetPosesResponse_BodyPosesEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit GetPosesResponse_BodyPosesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_GetPosesResponse_BodyPosesEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_component_2fposetracker_2fv1_2fpose_5ftracker_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 73,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull GetPosesResponse_BodyPosesEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class GetPosesResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:viam.component.posetracker.v1.GetPosesResponse) */ {
 public:
  inline GetPosesResponse() : GetPosesResponse(nullptr) {}
  ~GetPosesResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetPosesResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetPosesResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetPosesResponse(::google::protobuf::internal::ConstantInitialized);

  inline GetPosesResponse(const GetPosesResponse& from) : GetPosesResponse(nullptr, from) {}
  inline GetPosesResponse(GetPosesResponse&& from) noexcept
      : GetPosesResponse(nullptr, ::std::move(from)) {}
  inline GetPosesResponse& operator=(const GetPosesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPosesResponse& operator=(GetPosesResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPosesResponse& default_instance() {
    return *reinterpret_cast<const GetPosesResponse*>(
        &_GetPosesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GetPosesResponse& a, GetPosesResponse& b) { a.Swap(&b); }
  inline void Swap(GetPosesResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPosesResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPosesResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetPosesResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetPosesResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetPosesResponse& from) { GetPosesResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetPosesResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "viam.component.posetracker.v1.GetPosesResponse"; }

  explicit GetPosesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetPosesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetPosesResponse& from);
  GetPosesResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetPosesResponse&& from) noexcept
      : GetPosesResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBodyPosesFieldNumber = 1,
  };
  // map<string, .viam.common.v1.PoseInFrame> body_poses = 1 [json_name = "bodyPoses"];
  int body_poses_size() const;
  private:
  int _internal_body_poses_size() const;

  public:
  void clear_body_poses() ;
  const ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>& body_poses() const;
  ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>* PROTOBUF_NONNULL mutable_body_poses();

  private:
  const ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>& _internal_body_poses() const;
  ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>* PROTOBUF_NONNULL _internal_mutable_body_poses();

  public:
  // @@protoc_insertion_point(class_scope:viam.component.posetracker.v1.GetPosesResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   2, 65,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetPosesResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<GetPosesResponse_BodyPosesEntry_DoNotUse, ::std::string, ::viam::common::v1::PoseInFrame,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        body_poses_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_component_2fposetracker_2fv1_2fpose_5ftracker_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetPosesResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GetPosesRequest

// string name = 1 [json_name = "name"];
inline void GetPosesRequest::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& GetPosesRequest::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:viam.component.posetracker.v1.GetPosesRequest.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GetPosesRequest::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:viam.component.posetracker.v1.GetPosesRequest.name)
}
inline ::std::string* PROTOBUF_NONNULL GetPosesRequest::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:viam.component.posetracker.v1.GetPosesRequest.name)
  return _s;
}
inline const ::std::string& GetPosesRequest::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void GetPosesRequest::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GetPosesRequest::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GetPosesRequest::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:viam.component.posetracker.v1.GetPosesRequest.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void GetPosesRequest::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:viam.component.posetracker.v1.GetPosesRequest.name)
}

// repeated string body_names = 2 [json_name = "bodyNames"];
inline int GetPosesRequest::_internal_body_names_size() const {
  return _internal_body_names().size();
}
inline int GetPosesRequest::body_names_size() const {
  return _internal_body_names_size();
}
inline void GetPosesRequest::clear_body_names() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_names_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL GetPosesRequest::add_body_names()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_body_names()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:viam.component.posetracker.v1.GetPosesRequest.body_names)
  return _s;
}
inline const ::std::string& GetPosesRequest::body_names(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:viam.component.posetracker.v1.GetPosesRequest.body_names)
  return _internal_body_names().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL GetPosesRequest::mutable_body_names(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:viam.component.posetracker.v1.GetPosesRequest.body_names)
  return _internal_mutable_body_names()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void GetPosesRequest::set_body_names(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_body_names()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:viam.component.posetracker.v1.GetPosesRequest.body_names)
}
template <typename Arg_, typename... Args_>
inline void GetPosesRequest::add_body_names(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_body_names(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:viam.component.posetracker.v1.GetPosesRequest.body_names)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& GetPosesRequest::body_names()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:viam.component.posetracker.v1.GetPosesRequest.body_names)
  return _internal_body_names();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
GetPosesRequest::mutable_body_names() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:viam.component.posetracker.v1.GetPosesRequest.body_names)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_body_names();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
GetPosesRequest::_internal_body_names() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_names_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
GetPosesRequest::_internal_mutable_body_names() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.body_names_;
}

// .google.protobuf.Struct extra = 99 [json_name = "extra"];
inline bool GetPosesRequest::has_extra() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.extra_ != nullptr);
  return value;
}
inline const ::google::protobuf::Struct& GetPosesRequest::_internal_extra() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Struct* p = _impl_.extra_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Struct&>(::google::protobuf::_Struct_default_instance_);
}
inline const ::google::protobuf::Struct& GetPosesRequest::extra() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:viam.component.posetracker.v1.GetPosesRequest.extra)
  return _internal_extra();
}
inline void GetPosesRequest::unsafe_arena_set_allocated_extra(
    ::google::protobuf::Struct* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.extra_);
  }
  _impl_.extra_ = reinterpret_cast<::google::protobuf::Struct*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:viam.component.posetracker.v1.GetPosesRequest.extra)
}
inline ::google::protobuf::Struct* PROTOBUF_NULLABLE GetPosesRequest::release_extra() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Struct* released = _impl_.extra_;
  _impl_.extra_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Struct* PROTOBUF_NULLABLE GetPosesRequest::unsafe_arena_release_extra() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:viam.component.posetracker.v1.GetPosesRequest.extra)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Struct* temp = _impl_.extra_;
  _impl_.extra_ = nullptr;
  return temp;
}
inline ::google::protobuf::Struct* PROTOBUF_NONNULL GetPosesRequest::_internal_mutable_extra() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.extra_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Struct>(GetArena());
    _impl_.extra_ = reinterpret_cast<::google::protobuf::Struct*>(p);
  }
  return _impl_.extra_;
}
inline ::google::protobuf::Struct* PROTOBUF_NONNULL GetPosesRequest::mutable_extra()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::google::protobuf::Struct* _msg = _internal_mutable_extra();
  // @@protoc_insertion_point(field_mutable:viam.component.posetracker.v1.GetPosesRequest.extra)
  return _msg;
}
inline void GetPosesRequest::set_allocated_extra(::google::protobuf::Struct* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.extra_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.extra_ = reinterpret_cast<::google::protobuf::Struct*>(value);
  // @@protoc_insertion_point(field_set_allocated:viam.component.posetracker.v1.GetPosesRequest.extra)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GetPosesResponse

// map<string, .viam.common.v1.PoseInFrame> body_poses = 1 [json_name = "bodyPoses"];
inline int GetPosesResponse::_internal_body_poses_size() const {
  return _internal_body_poses().size();
}
inline int GetPosesResponse::body_poses_size() const {
  return _internal_body_poses_size();
}
inline const ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>& GetPosesResponse::_internal_body_poses() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_poses_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>& GetPosesResponse::body_poses() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:viam.component.posetracker.v1.GetPosesResponse.body_poses)
  return _internal_body_poses();
}
inline ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>* PROTOBUF_NONNULL GetPosesResponse::_internal_mutable_body_poses() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.body_poses_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::viam::common::v1::PoseInFrame>* PROTOBUF_NONNULL GetPosesResponse::mutable_body_poses()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_map:viam.component.posetracker.v1.GetPosesResponse.body_poses)
  return _internal_mutable_body_poses();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace posetracker
}  // namespace component
}  // namespace viam


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // component_2fposetracker_2fv1_2fpose_5ftracker_2eproto_2epb_2eh
