on:
  workflow_dispatch:
  push: # DONOTMERGE

env:
  CMAKE_VERSION: 3.27.4

jobs:
  build-deb:
    strategy:
      matrix:
        include:
        - container: debian:bookworm
          label: bookworm-aarch64
          runs-on: buildjet-4vcpu-ubuntu-2204-arm
        - container: debian:bookworm
          label: bookworm-x86_64
          runs-on: buildjet-4vcpu-ubuntu-2204
    container: ${{ matrix.container }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - name: depends
      run: |
        apt-get update
        apt-get install -qqy \
                build-essential \
                libabsl-dev \
                libboost-all-dev \
                libgrpc++-dev \
                libprotobuf-dev \
                pkg-config \
                ninja-build \
                protobuf-compiler-grpc \
                git \
                wget
    - name: download cmake
      run: |
        ARCH=$(uname -m)
        wget --quiet https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-$ARCH.sh
        chmod +x cmake-${CMAKE_VERSION}-linux-$ARCH.sh
        ./cmake-${CMAKE_VERSION}-linux-$ARCH.sh --skip-license --prefix=/usr
    - name: remove examples
      # todo(RSDK-4735): no longer needed once 'all' is cleaned up
      run: sed -i '/add_subdirectory.examples/d' src/viam/CMakeLists.txt
    - name: cmake
      run: cmake -S . -B ./build -G Ninja -DCMAKE_INSTALL_PREFIX=/usr
    - name: build
      run: |
        cmake --build ./build --target libviamsdk.so
        cpack -B ./build
    - uses: actions/upload-artifact@v3
      with:
        name: debian-${{ matrix.label }}
        path: build/viam-cpp-sdk-*.deb
