name: Update Protos + Open PR

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - protos-updated

jobs:
  update-protos:
    if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/cpp-sdk-system-debian:bookworm
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Install workflow tools
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install jq unzip

      - uses: bufbuild/buf-setup-action@v1.50.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update buf
        run: |
          cmake -B build -DVIAMCPPSDK_USE_DYNAMIC_PROTOS=ON && cmake --build ./build --target update-buf

      - name: Generate buf
        run: |
          cmake -B build -DVIAMCPPSDK_USE_DYNAMIC_PROTOS=ON && cmake --build ./build --target update-static-protos

      - name: Set event-specific variables (repository_dispatch)
        if: github.event_name == 'repository_dispatch'
        id: set_tag_repository_dispatch
        run: |
          echo "API_PROTO_TAG_VERSION=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
          echo "PROTO_REPO_NAME=${{ github.event.client_payload.repo_name }}" >> $GITHUB_ENV
          echo "PROTO_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV

      - name: Set event-specific variables (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        id: set_tag_workflow_dispatch
        run: |
          TAG=$(curl --silent https://api.github.com/repos/viamrobotics/api/tags | jq -r '.[0].name')
          echo "API_PROTO_TAG_VERSION=${TAG}" >> $GITHUB_ENV
          echo "PROTO_REPO_NAME=viamrobotics/api" >> $GITHUB_ENV
          echo "PROTO_SHA=${TAG}" >> $GITHUB_ENV

      - name: Update proto tag
        run: echo "${{ env.API_PROTO_TAG_VERSION }}" > src/viam/api/api_proto_tag.lock

      - name: Add + Commit + Open PR
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: '[WORKFLOW] Updating protos from ${{ env.PROTO_REPO_NAME }}, commit: ${{ env.PROTO_SHA }}'
          branch: 'workflow/update-protos'
          add-paths: |
            src/viam/api/*
            buf.lock
          delete-branch: true
          title: Automated Protos Update
          body: This is an auto-generated PR to update proto definitions. Check the commits to see which repos and commits are responsible for the changes
          assignees: stuqdog
          reviewers: stuqdog
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Notify slack of failure
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() }}
        with:
          payload: |
            {
              "text": "CPP SDK update protos job has failed",
              "username": "CPP SDK",
              "icon_url": "https://media.tenor.com/bZMubztJxGkAAAAe/charlie-brown-walking-charlie-brown.png"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEAM_SDK_WEBHOOK_URL }}
