name: Update Protos + Open PR

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - protos-updated

jobs:
  update-protos:
    if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/rdk-devenv:amd64
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      # note (erodkin): these dependencies were cribbed from what we use to build the SDK
      # in the release job. Only very cursory effort was made to prune.
      - name: install dependencies
        run: |
          sudo apt-get update && apt-get upgrade -y
          apt-get install -y software-properties-common
          apt-add-repository -y 'deb https://archive.debian.org/debian bullseye-backports main'
          apt-get update
          apt-get -y dist-upgrade
          DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
              build-essential \
              ca-certificates \
              curl \
              g++ \
              gdb \
              gnupg \
              gpg \
              less \
              libboost-all-dev \
              libgrpc++-dev \
              libprotobuf-dev \
              libssl-dev \
              ninja-build \
              pkg-config \
              protobuf-compiler \
              protobuf-compiler-grpc \
              software-properties-common \
              sudo \
              wget \

      - uses: MarkusJx/install-boost@v2.4.4
        with:
          boost_version: 1.81.0
          platform_version: 22.04

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.25.2
          ninjaVersion: 1.11.1

      - uses: bufbuild/buf-setup-action@v1.50.0

      - uses: arduino/setup-protoc@v1

      - name: Update buf
        run: |
          cmake -B build -DVIAMCPPSDK_USE_DYNAMIC_PROTOS=ON && cmake --build ./build --target update-buf
        env:
          BOOST_ROOT: ${{ github.workspace }}/boost/boost

      - name: Generate buf
        run: |
          cmake -B build -DVIAMCPPSDK_USE_DYNAMIC_PROTOS=ON && cmake --build ./build --target update-static-protos
        env:
          BOOST_ROOT: ${{ github.workspace }}/boost/boost

      - name: cleanup
        run: rm -rf boost/

      - name: Set event-specific variables (repository_dispatch)
        if: github.event_name == 'repository_dispatch'
        id: set_tag_repository_dispatch
        run: |
          echo "API_PROTO_TAG_VERSION=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
          echo "PROTO_REPO_NAME=${{ github.event.client_payload.repo_name }}" >> $GITHUB_ENV
          echo "PROTO_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV

      - name: Set event-specific variables (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        id: set_tag_workflow_dispatch
        run: |
          TAG=$(curl --silent https://api.github.com/repos/viamrobotics/api/tags | jq -r '.[0].name')
          echo "API_PROTO_TAG_VERSION=${TAG}" >> $GITHUB_ENV
          echo "PROTO_REPO_NAME=viamrobotics/api" >> $GITHUB_ENV
          echo "PROTO_SHA=${TAG}" >> $GITHUB_ENV

      - name: Update proto tag
        run: echo "${{ env.API_PROTO_TAG_VERSION }}" > src/viam/api/api_proto_tag.lock

      - name: Add + Commit + Open PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: '[WORKFLOW] Updating protos from ${{ env.PROTO_REPO_NAME }}, commit: ${{ env.PROTO_SHA }}'
          branch: 'workflow/update-protos'
          add-paths: src/viam/api/*
          delete-branch: true
          title: Automated Protos Update
          body: This is an auto-generated PR to update proto definitions. Check the commits to see which repos and commits are responsible for the changes
          assignees: stuqdog
          reviewers: stuqdog
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Notify slack of failure
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() }}
        with:
          payload: |
            {
              "text": "CPP SDK update protos job has failed",
              "username": "CPP SDK",
              "icon_url": "https://media.tenor.com/bZMubztJxGkAAAAe/charlie-brown-walking-charlie-brown.png"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEAM_SDK_WEBHOOK_URL }}
